# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_auto_20170220_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
