# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_product_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uid',
        ),
    ]
